data:
  data_dir: 'data/processed/train/lung_crops/lung'
  opacity_masks_dir: 'data/processed/train/lung_crops/opacity_masks'
  folds_df: 'data/processed/stratified_group_kfold_split_5_42.csv'
  num_classes: 4
  idx_fold: 0
  num_folds: 5
  dataset_name: 'StudySegmentationDataset'
  image_resolution: 512

model:
  arch: 'SegmentationModel'
  params:
    encoder_name: 'efficientnet_b3'
    num_classes: 4
    pretrained: True

train:
  batch_size: 32
  overfit_single_batch: False
  num_epochs: 30
  snapshots: 1
  checkpoint_path: '/home/yousef/deep-learning/kaggle/covid/trained-models/47/2021-07-04_06.42.53/fold-0/checkpoints/best_model.pth'

test:
  batch_size: 32
  cls_threshold: 0.5
  tta:
    horizontal: False
    vertical: False

# transforms hard-coded same as 1st place finish in melanoma

loss:
  name: "CrossEntropy"
  params:
    reduction: 'none'
    seg_multiplier: 10

optimizer:
  name: 'Adam'
  params:
    lr: 1.0e-4

scheduler:
  name: ''
  params:
    max_lr: 1.0e-2
    div_factor: 10
    pct_start: 0.0
    final_div_factor: 100

num_workers: 8
device: 'cuda:0'
multi_gpu: False
debug: False
work_dir: 'build/'
