data:
  data_dir: 'data/processed/train/png_div_2'
  folds_df: 'data/processed/stratified_group_kfold_split_5_42.csv'
  num_classes: 4
  idx_fold: 4
  num_folds: 5
  dataset_name: 'StudyClassificationDataset'
  image_resolution: 600

model:
  arch: 'ClassificationModel'
  params:
    encoder_name: 'efficientnet-b7'
    num_classes: 4
    pretrained: True

train:
  batch_size: 32
  overfit_single_batch: False
  num_epochs: 20
  snapshots: 1

test:
  batch_size: 32
  cls_threshold: 0.5
  tta:
    horizontal: False
    vertical: False

transforms:
  train:
    HorizontalFlip: True
    VerticalFlip: True

  test:
    AssertShape:
      p: 1.0
      height: 600
      width: 600

loss:
  name: "CrossEntropy"
  params:
    reduction: 'none'

optimizer:
  name: 'Adam'
  params:
    lr: 0.001

scheduler:
  name: 'plateau'
  params:
    patience: 3
    factor: 10
    min_lr: 1.0e-6

num_workers: 8
device: 'cuda:0'
multi_gpu: False
debug: False
work_dir: 'build/'
