data:
  data_dir: '/home/yousef/deep-learning/kaggle/covid/data/processed/train/lung_crops/lung'
  opacity_masks_dir: '/home/yousef/deep-learning/kaggle/covid/data/processed/train/lung_crops/opacity_masks'
  folds_df: '/home/yousef/deep-learning/kaggle/covid/data/processed/stratified_group_kfold_split_5_42.csv'
  num_classes: 4
  idx_fold: 0
  num_folds: 5
  dataset_name: 'StudySegmentationDataset'
  image_resolution: 512

model:
  arch: 'GAIN'
  params:
    efnet_encoder_name: 'efficientnet_b3'
    num_classes: 4
    pretrained: True
    gradient_layer_name: 'blocks.6.1'
    omega: 1.0
    sigma: 0.5

train:
  batch_size: 8
  overfit_single_batch: False
  num_epochs: 10
  snapshots: 1

test:
  batch_size: 8
  cls_threshold: 0.5
  tta:
    horizontal: False
    vertical: False

transforms:
  train:
    HorizontalFlip: True
    VerticalFlip: True
    Transpose: True
    BrightnessContrast:
      p: 0.3
    HueSaturationValue:
      p: 0.2
    Blur: True
    Noise: True
    ShiftScaleRotate:
      p: 0.3

loss:
  name: "CrossEntropy"
  params:
    reduction: 'none'

optimizer:
  name: 'Adam'
  params:
    lr: 1.0e-4

scheduler:
  name: 'onecycle'
  params:
    max_lr: 1.0e-4
    div_factor: 10
    pct_start: 0.3
    final_div_factor: 100

num_workers: 4
device: 'cuda:0'
multi_gpu: False
debug: False
work_dir: 'build/'
